### ISSUE TITLE
Regression issue - no labels or annotations are set by default

### ISSUE THREAD

**Issue by alexellis** [openfaas-incubator/openfaas-operator#49]
## Problem

Regression issue - no labels or annotations are set when deploying functions.

See notes in linked PR review comments for more details.

## Reproducing the issue

* Deploy the latest operator version

```
helm repo update  && \
helm upgrade openfaas --install openfaas/openfaas    \
 --namespace openfaas      --set basic_auth=true   \
  --set functionNamespace=openfaas-fn --set operator.create=true
```

* Deploy a function

```
faas-cli store deploy figlet   -g 127.0.0.1:31112
```

No labels or annotations are added.

```
$ curl http://127.0.0.1:31112/system/functions
[{"name":"figlet","image":"functions/figlet:0.1","invocationCount":0,
"replicas":1,"envProcess":"
","availableReplicas":1,
"labels":{},"annotations":null}]
```

Reported in review comments for #48 

There should always be one annotation to stop Weave Cloud scraping functions and > 1 labels present. 

## Update

I see these labels/annotations on the Deployment object, but they are not returned via the REST API which is a discrepancy with the faas-netes/faas-swarm and other providers.

**Comment by alexellis** [comment]
Attention @ewilde @stefanprodan @LucasRoesler

**Comment by stefanprodan** [comment]
This is the correct behaviour in my opinion since the operator API returns the function custom resource definition not what's being materialised in the deployment spec. If you add labels and annotations in the function definition those will be present in the response.

**Comment by LucasRoesler** [comment]
Currently the labels and annotaitons are pulled directly from the Function CRD 

https://github.com/openfaas-incubator/openfaas-operator/blob/5548b019fe49b2f7f7d31f354f6825c2546ed751/pkg/server/list.go#L14-L42

And those labels and annotaitons would come from the request that is sent by the CLI 

https://github.com/openfaas-incubator/openfaas-operator/blob/5548b019fe49b2f7f7d31f354f6825c2546ed751/pkg/server/apply.go#L18-L48

Which would be empty with this command `faas-cli store deploy figlet   -g 127.0.0.1:31112` since you don't specify any labels via the CLI and the figlet stack doesn't specify any.  I don't see any code in the server apply handler to add any preset labels or annotations

**Comment by stefanprodan** [comment]
@LucasRoesler yes that's the case and it's not a mistake, I did this on purpose, there is no need in my opinion to query the deployment spec.

**Comment by LucasRoesler** [comment]
I see your point, we just submitted comments nearly at the same time :) I agree that the current behavior is correct as implemented and semantically correct.  

Internal labels/annotations that can not be modified by the user, probably don't need to be reported in the API.  

If we wanted to do that in the Operator, then we should probably modify the Function spec before submitting it to k8s (like a middleware), so that those values are actually part of the spec.

**Comment by stefanprodan** [comment]
We should not expose implementation details to our end user over the API. The fact that we add "special" labels and annotations to the deployment are an OpenFaaS internal thing not user facing. 

@alexellis why do you consider this a bug and high prio?

**Comment by alexellis** [comment]
This behavior is incorrect and inconsistent, but after further analysis I can remove the labels.

**Comment by alexellis** [comment]
Derek close
